[WIP] Merge demo branch into master branch
swsnu/swpp2020-team4 pull request #82
Opened 2020-11-15 15:10 UTC by promet99

2020-11-16 02:34 UTC, polarcoke2 requested changes
17 / 41 files are done. 나머지는 좀 이따가 마저 함 @ChanHyup98

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +            for index, stock_tuple in enumerate(self.buy_amount_list):
same here. Index is not used

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +                except IndexError:
Please specify the error message for debugging

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +    def make_scope(self):
method docstring and return value

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +        universe = self.universe
universe is not used in here

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +    def make_amount_list(self, opt, chosen_stocks):
method docstring, function parameter type, and return value missing

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +        if opt == "buy":
for security, we need to change the operations's type from string to enum

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +        if opt == "buy":
If not, we need to add some exceptional cases.

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +    def make_daily_report(self):
method docstring, return type

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +    def track_max_min(self, profit):
Please specify the rules used in here. What does 'eq', 'gt', 'lt' mean and how are they used?

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +    def track_max_min(self, profit):
Method docstring and return value

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +    def report_result(self, start, end):
method docstring, method parameter type, return type

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +    def calculate_mdd(self):
method docstring and return type

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +            if max_min_list[-1 * i] - min_element > max_diff:
max diff를 계산하는 데 min_element가 쓰이는데, 이 if statement가 나중에 가야 하는 건 아니야?

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +    def calculate_alpha(self, start, end):
method docstring, parameter typing, and return type

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/sandbox.py
> +        for index, date in enumerate(self.date_rows):
여기도 index는 쓰이지 않음

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/sandbox.py
> +            back_tester.make_scope()
why does ```make_scope()``` call is later than the ```make_sell_order()``` and ```make_buy_order()```?

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/sandbox.py
> +        self.run()
디자인적으로는 뭔가를 실행하는 코드를 짤 때
- prepare (Prepare execution, do housekeeping stuff and load necessary information)
- execute (Public wrapper function to protect actual executing function)
  - doExecute (Private function which actually does the execution)
- cleanUp (Teardown, destroy objects and remove loaded information)

의 3단계로 쪼개서 짜는게 가장 깔끔하고 덜 복잡함. 지금 코드쪽을 보면 이게 다 섞여 있는 것 같음. 특히 멀티프로세싱쪽으로 코드 리팩토링할 거 생각하면 이거를 좀 고칠 필요는 있는 것 같아. 나중에 자세하게 얘기할 필요성이 있음

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/sandbox.py
> +    def run(self):
method docstring and return value

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/sandbox.py
>      def get_trading_dates(self):
return value

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/wallet/wallet.py
> +    def __init__(self, budget: float, stock_id_to_coin: Optional[Dict[int, StockCoin]] = None):
return value

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/wallet/wallet.py
> +            except IndexError:
Please specify error message

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/lib/wallet/wallet.py
> +    def get_profit(self):
method docstring and return value

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/models/evaluation/report.py
> +    daily_profit = models.TextField()
profit이면 text보다는 float이 더 낫지 않을까 하는 개인적인 생각

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/serializers/algorithm/algorithm_serializer.py
> +        fields = ['id', 'name', 'description', 'author', 'is_public', 'snippet_scope', 'snippet_sell', 'snippet_buy',
만약 이게 모든 field라면, ```fields = '__all__'``` 를 쓰는 방법도 있음. 아니면 exclude도 찾아봐

2020-11-16 02:34 UTC, polarcoke2 commented on back/qc_api/temp.py
> +if __name__=='main':
이 파일의 정체는?

2020-11-16 02:47 UTC, ChanHyup98 commented on back/qc_api/temp.py
> +if __name__=='main':
master에 있는 쓸모없는 파일인데 conflict때매 다시 추가됨. 
머지 후에 master에서 바로 delete commit 날릴예정

2020-11-16 02:49 UTC, ChanHyup98 commented on back/qc_api/models/evaluation/report.py
> +    daily_profit = models.TextField()
저거 array야! [{2020-01-01: 104.342}, {2020-01-02: 103.123}] 이런식이고 이걸 프론트로 전달하면 이 데이터에 기반해서 
그래프가 그려지는것

2020-11-16 02:58 UTC, ChanHyup98 commented on back/qc_api/lib/backtest/backtester.py
> +        self.report = {
def make_daily_report(self):
        profit = self.wallet.get_profit()
        self.report.get("transaction_log").append(self.wallet.get_transaction_log(self.today))
        self.report.get("daily_profit").append({"date": str(self.today), "profit": profit})
        self.track_max_min(profit=profit)

나중에 이런식으로 저 self.report 의 각 key들에 대해서 daily backtest stat이 업데이트 될 예정이라서 저렇게했음

2020-11-16 02:59 UTC, ChanHyup98 commented on back/qc_api/lib/backtest/backtester.py
> +            for index, stock_tuple in enumerate(self.sell_amount_list):
저거 저렇게 안해두면 유저가 코드를 작성할때 (예를 들어 scope 에 접근하고 싶으면) 직접 self.scope라고 써야하잖아
약간 user-friendly한 namespace를 제공하기 위한 방편임.

2020-11-16 03:01 UTC, ChanHyup98 commented on back/qc_api/lib/sandbox.py
> +        for index, date in enumerate(self.date_rows):
저거 저렇게 안해두면 유저가 코드를 작성할때 (예를 들어 scope 에 접근하고 싶으면) 직접 self.scope라고 써야하잖아
약간 user-friendly한 namespace를 제공하기 위한 방편임.

2020-11-16 03:02 UTC, ChanHyup98 commented on back/qc_api/lib/sandbox.py
> +        self.run()
이건 새 이슈 만들어놓을까?

2020-11-16 03:04 UTC, ChanHyup98 commented on back/qc_api/lib/sandbox.py
> +            back_tester.make_scope()
make_scope()는 오늘 데이터 기준으로 '내일 뭘 탐색할지' 를 정하는거고
make_sell & buy_order()는 'make_scope()가 어제 뭘살지' 결정해놓은걸 (self.scope 에 저장되어있음) 기반으로 '오늘 뭘 사고팔지' 결정하는 거니까!
@polarcoke2

2020-11-16 03:20 UTC, ChanHyup98 commented on back/qc_api/lib/backtest/backtester.py
> +            if max_min_list[-1 * i] - min_element > max_diff:
나중에 docstring에도 적겠지만 이 함수는 backtest의 daily profit 들의 local minima, maxima를 담고 있는 array에서 
   1. 맨 뒤에서부터 맨 앞까지 훑고 지나가는 포인터 (max_min_list[-1*i]), 
   2. 현재 max_min_list[-1*i] 위치의 오른쪽에서 가장 작은 놈을 가르키는 포인터
두개로 구성됨. 

[3, 5, 1, 9, 3, 2, 8, 7] <= 이 array를 input으로 한다고 치면 

initial condition:  max_diff = 8-7 -> 1, min_element = 7
first iteration: max_diff = 1>7-7 -> 1, min_element = 7
second: max_diff = 1 <=8-7 ->1, min_element = 7
third: max_diff = 1 > 2-7 -> 1, min_element =2
fourth: max_diff = 1 <= 3-2 -> 1, min_element = 2
fifth: max_diff = 1 < 9-2 -> 7, min_element = 2
sixth: max_diff = 7 > 1-2 -> 7, min_element = 1
seventh: max_diff = 7 > 5-1 -> 7, min_element = 4
... 
이런식으로 backtest 기간 중 최대 낙폭 (MDD) 의 값이 7 임을 알 수 있게됨. 
딱히 뭘 먼저 계산하든 상관없는거같음

2020-11-16 03:22 UTC, ChanHyup98 commented on back/qc_api/lib/backtest/backtester.py
> +            if max_min_list[-1 * i] - min_element > max_diff:
다시 생각해보니까 논리적으로 min_element를 먼저 update 하면 min_element의 domain이 exclusive 에서 inclusive로 바뀌는 셈이네. 그래도 계산결과는 동일하겠지만 아마

2020-11-16 04:02 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +        self.report = {
list는 이해함 나는 alpha나 mdd 같은 statistics를 물어보는 거긴 했어

2020-11-16 04:05 UTC, polarcoke2 commented on back/qc_api/lib/sandbox.py
> +        self.run()
ㅇㅇ Refactor backtesting code 정도로 만들어놓고 샐러리 라이브러리 도입할 때 함께 해결하면 좋을 듯

2020-11-16 04:06 UTC, polarcoke2 commented on back/qc_api/models/evaluation/report.py
> +    daily_profit = models.TextField()
ㅇㅋㅇㅋ

2020-11-16 04:07 UTC, ChanHyup98 commented on back/qc_api/lib/backtest/backtester.py
> +        self.report = {
어 근데 딱히 nullable하지 않은 값들이라서 initialize 해놓은거임 걔네는

2020-11-16 05:35 UTC, ChanHyup98 commented on back/qc_api/lib/sandbox.py
> +        self.run()
#83

2020-11-16 05:36 UTC, ChanHyup98 commented on back/qc_api/lib/wallet/wallet.py
> +            except IndexError:
이거 index error가 deterministic함. 
기존에 wallet에 담아뒀던 주식이 어느날 상장폐지되버려서 접근할수가 없는 경우임. 그래서 따로 
error message 안 넣어주고 걍 coin.set_price(0) 해주는거야
@polarcoke2

2020-11-16 05:39 UTC, ChanHyup98 commented on back/qc_api/lib/backtest/backtester.py
> +        self.max_min_dict = {
밑에 이 dict를 사용하는 function에 주석 달면 될까? 
아니면 그냥 여기 설명할까?

2020-11-16 05:43 UTC, ChanHyup98 commented on back/qc_api/lib/backtest/backtester.py
> +            scope = dict(locals(), **globals())
걍 exec_dict 가 돌리는 코드가 local variable들이랑 global variable들에 접근할 수 있다는 의미일껄?

2020-11-16 07:55 UTC, polarcoke2 requested changes

2020-11-16 07:55 UTC, polarcoke2 commented on front/src/Component/dashboard/backtest/mock.js
> +export const createData = (name, calories, fat, carbs, protein) => {
👍

2020-11-16 07:55 UTC, polarcoke2 commented on front/src/Component/dashboard/backtest/newBackTestForm.js
> +  const [startingBudget, setStartingBudget] = useState(2000)
여기서 2000은 dummy value야?

2020-11-16 07:55 UTC, polarcoke2 commented on front/src/Component/dashboard/backtest/newBackTestForm.js
> +        disabled={startDate === '' || endDate === '' || startDate >= endDate || startingBudget <= 0}
👍

2020-11-16 07:55 UTC, polarcoke2 commented on front/src/page/dashboardPage.jsx
> +    const [simulationData, setSimulationData] = useState({
이것들을 지금 둔 상태로 merge할 지, 아니면 지우고 merge할지 얘기해봐야 하지 않을까? @promet99 너의 의견을 따름

2020-11-16 07:55 UTC, polarcoke2 commented on front/src/page/dashboardPage.jsx
> +    const [simulationData, setSimulationData] = useState({
그리고 실제 코드가 이렇게까지 길어지진 않겠지? 길어진다면 articleList 만들었던 것 처럼 list component로 wrapping 하는 것도 괜찮을 것 같음.

2020-11-16 07:55 UTC, polarcoke2 commented on front/src/page/dashboardPage.jsx
>  export const DashboardPage = () => {
이 파일이 전반적으로 너무 길어서 쪼갤 수 있는건 쪼개는 게 좋을 듯!

2020-11-16 07:55 UTC, polarcoke2 commented on front/src/page/writePage.jsx
>    const handleSubmitSnippet = (i) => {
여기 undefined가 있는 이유는 뭐야?

2020-11-16 07:55 UTC, polarcoke2 commented on front/src/page/writePage.jsx
>    const handleSubmitSnippet = (i) => {
indexing을 위해서인가

2020-11-16 07:55 UTC, polarcoke2 commented on front/src/page/writePage.jsx
> +    // TODO: feedback message?
validate button을 눌렀을 때 콘솔이나 코드 주석으로 거로 error message가 뜨거나, 잘못된 부분을 표시해주는 기능이 추가되어야 할 것 같긴 함

2020-11-16 07:55 UTC, polarcoke2 commented on front/src/store/actions/snippet.js
> +      if (response.status === 201) {
200이 아니라 201이 맞아? 백앤드에서는 200으로 본 것 같음

2020-11-16 08:12 UTC, ChanHyup98 commented on back/qc_api/views/auth/auth_views.py
> +        if 'UNIQUE constraint' in str(e.args):
ㅁㄹ 내가한거아님 이따 살펴볼게

2020-11-16 08:15 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +        self.max_min_dict = {
주석으로 다는 게 더 좋을듯

2020-11-16 08:16 UTC, polarcoke2 commented on back/qc_api/lib/wallet/wallet.py
> +            except IndexError:
ㅇㅎ 그래도 저 정보가 user한테 넘어가야 한다면 따로 저장해놓는 건 필요할 듯

2020-11-16 08:16 UTC, polarcoke2 commented on back/qc_api/views/auth/auth_views.py
> +        if 'UNIQUE constraint' in str(e.args):
ㅇㅋ

2020-11-16 08:17 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +            scope = dict(locals(), **globals())
ㅇㅎ 그러면 user한테 Scope를 준다는 건 결국 저 local이랑 global을 다 access할 수 있다는 뜻이니까 조금만 제한해서 주는 건 필요할 듯

2020-11-16 08:19 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +            if max_min_list[-1 * i] - min_element > max_diff:
7th iteration에서 min elem 은 1이지? 4는 오타고?

2020-11-16 08:20 UTC, polarcoke2 commented on back/qc_api/lib/backtest/backtester.py
> +            if max_min_list[-1 * i] - min_element > max_diff:
뭔 뜻인지 알겠으 논리적으로 문제 없으면 ㅇㅋ

2020-11-16 08:20 UTC, polarcoke2 commented on back/qc_api/lib/sandbox.py
> +            back_tester.make_scope()
👍

2020-11-16 08:58 UTC, promet99 commented on front/src/Component/dashboard/backtest/newBackTestForm.js
> +  const [startingBudget, setStartingBudget] = useState(2000)
yes

2020-11-16 08:58 UTC, promet99 commented on front/src/Component/dashboard/backtest/mock.js
> +export const createData = (name, calories, fat, carbs, protein) => {
이건 목용이라 나중에 지워야지

2020-11-16 09:02 UTC, promet99 commented on front/src/page/writePage.jsx
>    const handleSubmitSnippet = (i) => {
맞아맞아. 이 부분은 나중에 개발할 때 추가해야지. 지금은 그냥 에러 안나게 해놨어

2020-11-17 03:45 UTC, ChanHyup98 commented on back/qc_api/lib/backtest/backtester.py
> +            scope = dict(locals(), **globals())
#83

2020-11-17 04:37 UTC, ChanHyup98 commented on back/qc_api/lib/backtest/backtester.py
> +    def __init__(self, algorithm, budget):
check

2020-11-17 04:38 UTC, ChanHyup98 commented on back/qc_api/lib/backtest/backtester.py
> +    def update_wallet(self):
check

2020-11-17 04:40 UTC, ChanHyup98 commented on back/qc_api/views/algorithm/algorithm_views.py
> +        "status": Report.BackTestStatus.DONE
#83

2020-11-17 05:13 UTC, ChanHyup98 commented on back/qc_api/lib/backtest/backtester.py
> +    def make_sell_order(self):
check

2020-11-17 05:59 UTC, promet99 commented on front/src/store/actions/snippet.js
> +      if (response.status === 201) {
post 인경우 201, get일때 200

2020-11-17 05:59 UTC, promet99 commented on front/src/page/dashboardPage.jsx
> +    const [simulationData, setSimulationData] = useState({
ㅇㅇㅇ 분리해야지

2020-11-17 06:00 UTC, merged